# Generated by Django 3.2.7 on 2021-10-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None)),
                ('tags', models.CharField(max_length=20)),
                ('image_url', models.TextField(default=None)),
                ('url_to', models.TextField(default=None)),
            ],
            options={
                'db_table': 'carousels',
            },
        ),
    ]
